ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/airline.lua ~/.config/nvim/lua/plugins/airline.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/airline_theme.lua ~/.config/nvim/lua/plugins/airline_theme.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/completion.lua ~/.config/nvim/lua/plugins/completion.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/copilot.lua ~/.config/nvim/lua/plugins/copilot.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/easymotion.lua ~/.config/nvim/lua/plugins/easymotion.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/fugitive.lua ~/.config/nvim/lua/plugins/fugitive.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/fzf.lua ~/.config/nvim/lua/plugins/fzf.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/gitgutter.lua ~/.config/nvim/lua/plugins/gitgutter.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/jumpcursor.lua ~/.config/nvim/lua/plugins/jumpcursor.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/lsp.lua ~/.config/nvim/lua/plugins/lsp.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/smoothcursor.lua ~/.config/nvim/lua/plugins/smoothcursor.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/sneak.lua ~/.config/nvim/lua/plugins/sneak.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/tagbar.lua ~/.config/nvim/lua/plugins/tagbar.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/tree.lua ~/.config/nvim/lua/plugins/tree.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/diffview.lua ~/.config/nvim/lua/plugins/diffview.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/toggleterm.lua ~/.config/nvim/lua/plugins/toggleterm.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/bufferline.lua ~/.config/nvim/lua/plugins/bufferline.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/tokyonight.lua ~/.config/nvim/lua/plugins/tokyonight.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/telescope.lua ~/.config/nvim/lua/plugins/telescope.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/nvim-window-picker.lua ~/.config/nvim/lua/plugins/nvim-window-picker.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/nvim-notify.lua ~/.config/nvim/lua/plugins/nvim-notify.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/noice.lua ~/.config/nvim/lua/plugins/noice.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/neo-tree.lua ~/.config/nvim/lua/plugins/neo-tree.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/lualine.lua ~/.config/nvim/lua/plugins/lualine.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/plugins/nvim-treesitter.lua ~/.config/nvim/lua/plugins/nvim-treesitter.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/config/lazy.lua ~/.config/nvim/lua/config/lazy.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/options.lua ~/.config/nvim/lua/options.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/keymaps.lua ~/.config/nvim/lua/keymaps.lua
ln -fnsv ~/migration/dotfiles/.config/nvim/lua/autocmd.lua ~/.config/nvim/lua/autocmd.lua

ln -fnsv ~/migration/dotfiles/.config/nvim/init.lua ~/.config/nvim/init.lua

ln -fnsv ~/migration/dotfiles/.config/nvim/lazy-lock.json ~/.config/nvim/lazy-lock.json
